// Dentro dos arrays, na propriedade "numero" a letra no final do código representa o nível de dificuldade da pergunta.
// Ex.: 1F (fácil), 1M (médio), 1D (difícil) 

let Friends = [
    {numero: "1F",
     pergunta: "Qual é o nome do personagem principal masculino em Friends?",
     a: "Ross Geller",
     b: "Chandler Bing",
     c: "Joey Tribbiani",
     d: "Phoebe Buffay",
     respCorreta: "a"
    },
    {numero: "2F",
     pergunta: "Qual é o nome do personagem que Ross tem um relacionamento romântico com a maior parte da série?",
     a: "Rachel Green",
     b: "Monica Geller",
     c: "Phoebe Buffay",
     d: "Janice Litman",
     respCorreta: "a"
    },
    {numero: "3F",
     pergunta: "Qual é o nome do personagem que é dono do café Central Perk?",
     a: "Gunther",
     b: "Joey Tribbiani",
     c: "Ross Geller",
     d: "Chandler Bing",
     respCorreta: "a"
    },
    {numero: "4F",
     pergunta: "Qual é o nome do ator que interpreta o personagem Chandler Bing?",
     a: "Matt LeBlanc",
     b: "David Schwimmer",
     c: "Matthew Perry",
     d: "Jennifer Aniston",
     respCorreta: "c"
    },
    {numero: "5F",
     pergunta: "Qual é o nome do ator que interpreta o personagem Ross Geller?",
     a: "Matt LeBlanc",
     b: "David Schwimmer",
     c: "Matthew Perry",
     d: "Jennifer Aniston",
     respCorreta: "b"
    },
    {numero: "6F",
     pergunta: "Qual é o nome da atriz que interpreta o personagem Rachel Green?",
     a: "Courteney Cox",
     b: "Lisa Kudrow",
     c: "Jennifer Aniston",
     d: "Christina Applegate",
     respCorreta: "c"
    },
    {numero: "7F",
     pergunta: "Qual é o nome do personagem que é o melhor amigo de Rachel na série?",
     a: "Phoebe Buffay",
     b: "Monica Geller",
     c: "Janice Litman",
     d: "Gunther",
     respCorreta: "b"
    },
    {numero: "8F",
     pergunta: "Qual é o nome do personagem que é o melhor amigo de Joey na série?",
     a: "Ross Geller",
     b: "Chandler Bing",
     c: "Phoebe Buffay",
     d: "Janice Litman",
     respCorreta: "b"
    },
    {numero: "9F",
     pergunta: "Qual é o nome do personagem que é o melhor amigo de Ross na série?",
     a: "Joey Tribbiani",
     b: "Chandler Bing",
     c: "Phoebe Buffay",
     d: "Janice Litman",
     respCorreta: "a"
    },
    {numero: "10F",
     pergunta: "Qual é o nome do personagem que é o melhor amigo de Chandler na série?",
     a: "Joey Tribbiani",
     b: "Ross Geller",
     c: "Phoebe Buffay",
     d: "Janice Litman",
     respCorreta: "a"
    },

    {numero: "1M",
     pergunta: "Qual é o nome do personagem que é o irmão de Ross na série?",
     a: "Jack Geller",
     b: "Ben Geller",
     c: "Richard Burke",
     d: "Robert Geller",
     respCorreta: "a"
    },
    {numero: "2M",
     pergunta: "Qual é a profissão de Rachel no início da série?",
     a: "Atriz",
     b: "Médica",
     c: "Garçonete",
     d: "Advogada",
     respCorreta: "c"
    },
    {numero: "3M",
     pergunta: "Quem é o pai de Ross e Monica?",
     a: "Jack Geller",
     b: "Ben Geller",
     c: "Richard Burke",
     d: "Robert Geller",
     respCorreta: "a"
    },
    {numero: "4M",
     pergunta: "Qual é o nome da mãe de Ross e Monica?",
     a: "Susan Geller",
     b: "Judy Geller",
     c: "Janice Geller",
     d: "Carol Willick",
     respCorreta: "b"
    },
    {numero: "5M",
     pergunta: "Qual é o nome do personagem que é o namorado de Phoebe durante a maior parte da série?",
     a: "Mike Hannigan",
     b: "David",
     c: "Gunther",
     d: "Parker",
     respCorreta: "a"
    },
    {numero: "6M",
     pergunta: "Qual é o nome do personagem que é o noivo de Rachel no final da série?",
     a: "Ross Geller",
     b: "Joey Tribbiani",
     c: "Chandler Bing",
     d: "Mike Hannigan",
     respCorreta: "a"
    },
    {numero: "7M",
     pergunta: "Qual é o nome do personagem que é o noivo de Monica no final da série?",
     a: "Ross Geller",
     b: "Joey Tribbiani",
     c: "Chandler Bing",
     d: "Mike Hannigan",
     respCorreta: "c"
    },
    {numero: "8M",
     pergunta: "Qual é o nome do personagem que é o filho de Ross e Rachel?",
     a: "Emma",
     b: "Ben",
     c: "Jack",
     d: "Michael",
     respCorreta: "a"
    },
    {numero: "9M",
     pergunta: "Qual é o nome do personagem que é o filho de Chandler e Monica?",
     a: "Emma",
     b: "Ben",
     c: "Jack",
     d: "Michael",
     respCorreta: "d"
    },
    {numero: "10M",
     pergunta: "Qual é o nome do personagem que é o marido de Phoebe no final da série?",
     a: "Mike Hannigan",
     b: "David",
     c: "Gunther",
     d: "Parker",
     respCorreta: "a"
    },
    {numero: "1D",
     pergunta: "Qual é o nome do personagem que é o melhor amigo de Rachel no trabalho durante a série?",
     a: "Mark",
     b: "Tag",
     c: "Paulo",
     d: "Gavin",
     respCorreta: "b"
    },
    {numero: "2D",
     pergunta: "Em qual episódio Ross diz 'Eu sou um amigo' ?",
     a: "The One With Ross's Denial",
     b: "The One With The Prom Video",
     c: "The One Where Ross And Rachel Take A Break",
     d: "The One With The Embryos",
     respCorreta: "a"
    },
    {numero: "3D",
     pergunta: "Qual é o nome do personagem que interpreta o irmão gêmeo de Phoebe?",
     a: "Ursula",
     b: "Frank Jr.",
     c: "Eric",
     d: "Robert",
     respCorreta: "b"
    },
    {numero: "4D",
     pergunta: "Qual é o nome do personagem que é o pai de Phoebe?",
     a: "Frank Buffay",
     b: "Phoebe Sr.",
     c: "Frank Sr.",
     d: "Phoebe Buffay Sr.",
     respCorreta: "a"
    },
    {numero: "5D",
     pergunta: "Em qual episódio Ross usa uma armadura medieval para se divertir com amigos?",
     a: "The One With Ross's Sandwich",
     b: "The One With Ross's Teeth",
     c: "The One With Ross's Wedding",
     d: "The One With Ross's Grant",
     respCorreta: "a"
    },
    {numero: "6D",
     pergunta: "Qual é o nome do personagem que é o irmão de Joey?",
     a: "Frank Tribbiani",
     b: "Gina Tribbiani",
     c: "Mary-Angela Tribbiani",
     d: "Bobbie Tribbiani",
     respCorreta: "d"
    },
    {numero: "7D",
     pergunta: "Qual é o nome do personagem que é o melhor amigo de Rachel e que ela se casa no final da série?",
     a: "Barry Farber",
     b: "Joshua Burgin",
     c: "Tag Jones",
     d: "Gavin Mitchell",
     respCorreta: "b"
    },
    {numero: "8D",
     pergunta: "Qual é o nome do personagem que é o chefe de Rachel no Central Perk?",
     a: "Gunther",
     b: "Paolo",
     c: "Mark",
     d: "Tag",
     respCorreta: "a"
    },
    {numero: "9D",
     pergunta: "Qual é o nome do personagem que é o melhor amigo de Ross e que se casa com Emily?",
     a: "Joey Tribbiani",
     b: "Chandler Bing",
     c: "Phoebe Buffay",
     d: "Janice Litman",
     respCorreta: "b"
    },
    {numero: "10D",
     pergunta: "Qual é o nome do personagem que é o chefe de Ross na série?",
     a: "Dr. Leonard Green",
     b: "Dr. Richard Burke",
     c: "Dr. Benjamin Hobart",
     d: "Dr. Roger",
     respCorreta: "a"
    },
]

let Duna_2021 = [
    {numero: "1F",
     pergunta: "Em que ano foi lançado o filme Duna?",
     a: "2018",
     b: "2020",
     c: "2019",
     d: "2021",
     respCorreta: "d"
    },
    {numero: "2F",
     pergunta: "Qual é o nome do protagonista do filme?",
     a: "Baron Harkonnen",
     b: "Frank Herbert",
     c: "Duke Leto",
     d: "Paul Atreides",
     respCorreta: "d"
    },
    {numero: "3F",
     pergunta: "Quem é o diretor do filme Duna?",
     a: "Jodorowsky",
     b: "David Lynch",
     c: "Denis Villeneuve",
     d: "Christopher Nolan",
     respCorreta: "c"
    },
    {numero: "4F",
     pergunta: "Qual é a força mental usada pelas Bene Gesserit?",
     a: "Precognição",
     b: "Presciência",
     c: "Intuição",
     d: "Pressentimento",
     respCorreta: "b"
    },
    {numero: "5F",
     pergunta: "Qual é o nome do pai de Paul Atreides?",
     a: "Thufir Hawat",
     b: "Baron Harkonnen",
     c: "Duke Leto",
     d: "Gurney Halleck",
     respCorreta: "c"
    },
    {numero: "6F",
     pergunta: "Qual é a especiaria mais valiosa encontrada em Duna?",
     a: "Melange",
     b: "Amarragem",
     c: "Spice",
     d: "Dune",
     respCorreta: "a"
    },
    {numero: "7F",
     pergunta: "Qual é o nome do filho de Paul Atreides?",
     a: "Ghanima",
     b: "Leto",
     c: "Alia",
     d: "Paul",
     respCorreta: "b"
    },
    {numero: "8F",
     pergunta: "Qual é o nome dos inimigos de Paul Atreides?",
     a: "Fremen",
     b: "Guild",
     c: "Harkonnen",
     d: "Bene Gesserit",
     respCorreta: "c"
    },
    {numero: "9F",
     pergunta: "Qual é o nome do planeta onde se passa a história?",
     a: "Caladan",
     b: "Arrakis",
     c: "Giedi Prime",
     d: "Pandora",
     respCorreta: "b"
    },
    {numero: "10F",
     pergunta: "Qual é o nome do personagem interpretado por Timothee Chalamet?",
     a: "Paul Atreides",
     b: "Duke Leto",
     c: "Baron Harkonnen",
     d: "Thufir Hawat",
     respCorreta: "a"
    },

    {numero: "1M",
     pergunta: "Qual é o nome do personagem interpretado por Rebecca Ferguson?",
     a: "Lady Jessica",
     b: "Ghanima",
     c: "Alia",
     d: "Chani",
     respCorreta: "a"
    },
    {numero: "2M",
    pergunta: "Qual é o nome do planeta natal de Paul Atreides no filme Duna?",
    a: "Arrakis",
    b: "Caladan",
    c: "Giedi Prime",
    d: "Coruscant",
    respCorreta: "b"
    },
    {numero: "3M",
    pergunta: "Qual é o nome do personagem interpretado por Oscar Isaac?",
    a: "Thufir Hawat",
    b: "Baron Vladimir Harkonnen",
    c: "Gurney Halleck",
    d: "Duke Leto Atreides",
    respCorreta: "d"
    },
    {numero: "4M",
    pergunta: "Qual é o nome do livro de Frank Herbert que inspirou o filme?",
    a: "The Children of Dune",
    b: "Dune",
    c: "God Emperor of Dune",
    d: "Heretics of Dune",
    respCorreta: "b"
    },
    {numero: "5M",
    pergunta: "Qual é a habilidade especial do personagem principal, Paul Atreides?",
    a: "Presciência",
    b: "Força sobre-humana",
    c: "Poderes mentais",
    d: "Invisibilidade",
    respCorreta: "a"
    },
    {numero: "6M",
    pergunta: "Qual é o nome da ordem religiosa presente no enredo?",
    a: "Bene Jesuits",
    b: "Bene Tleilax",
    c: "Bene Gesserit",
    d: "Bene Ecm",
    respCorreta: "c"
    },
    {numero: "7M",
    pergunta: "O que é a 'especiaria' que é um recurso muito valioso no planeta Arrakis?",
    a: "é um mineral raro",
    b: "é uma planta com propriedades medicinais",
    c: "é um combustível",
    d: "é uma droga psicoativa",
    respCorreta: "d"
    },
    {numero: "8M",
    pergunta: "Qual personagem é o líder da ordem Bene Gesserit?",
    a: "Lady Jessica",
    b: "Irulan Corrino",
    c: "Reverend Mother Ramallo",
    d: "Gaius Helen Mohiam",
    respCorreta: "d"
    },
    {numero: "9M",
    pergunta: "Qual é o nome do processo pelo qual o personagem principal é treinado para se tornar um líder?",
    a: "Treinamento de mentat",
    b: "Treinamento de combate",
    c: "Treinamento de comando",
    d: "Treinamento de presciência",
    respCorreta: "a"
    },
    {numero: "10M",
    pergunta: "Quem é o líder do grupo Fremen?",
    a: "Paul Atreides",
    b: "Thufir Hawat",
    c: "Stilgar",
    d: "Gurney Halleck",
    respCorreta: "c"
    },

    {numero: "1D",
    pergunta: "Qual é o nome do personagem interpretado por Javier Bardem?",
    a: "Gurney Halleck",
    b: "Stilgar",
    c: "Thufir Hawat",
    d: "Baron Vladimir Harkonnen",
    respCorreta: "b"
    },
    {numero: "2D",
    pergunta: "Qual é a relação entre os personagens Gurney Halleck e Paul Atreides?",
    a: "Gurney é o mentor de Paul",
    b: "Gurney é o irmão de Paul",
    c: "Gurney é o braço-direito de Paul",
    d: "Gurney é o inimigo de Paul",
    respCorreta: "c"
    },
    {numero: "3D",
    pergunta: "Qual é o nome do personagem interpretado por Zendaya no filme Duna?",
    a: "Irulan",
    b: "Chani",
    c: "Alia",
    d: "Jessica",
    respCorreta: "b"
    },
    {numero: "4D",
    pergunta: "Qual é o objetivo final dos personagens Bene Gesserit no filme Duna?",
    a: "Encontrar o escolhido",
    b: "Controlar o Império",
    c: "Controlar a especiaria",
    d: "Destruir o Império",
    respCorreta: "a"
    },
    {numero: "5D",
    pergunta: "Qual é o objetivo principal do personagem Paul Atreides?",
    a: "Extinguir a resistência local",
    b: "Vingar a morte de seu pai",
    c: "Liderar a rebelião contra o Império",
    d: "Controlar a produção da especiaria Melange",
    respCorreta: "d"
    },
]